name: Lobby
version: '${project.version}'
main: de.glowman554.lobby.LobbyMain
api-version: '1.20'
commands:
  lobby:
    permission: lobby.lobby
  l:
    permission: lobby.lobby
  hub:
    permission: lobby.lobby
